import assert from 'node:assert/strict';
import {createZone,pathfind,distance} from '../src/zone.js';
export default {name:'forest-art-zone',viewport:{width:390,height:844},async run({page,baseUrl,check,screenshot}){
 await page.goto(`${baseUrl}?seed=1`);
 await check('title, sharing metadata and atlases load',async()=>{await page.locator('#modal-action:enabled').waitFor({timeout:30000});assert.equal(await page.title(),'おいしいたると2〜濡食の森〜');assert.equal(await page.locator('meta[property="og:title"]').getAttribute('content'),'おいしいたると2〜濡食の森〜');assert.equal(await page.locator('meta[property="og:image"]').getAttribute('content'),'https://yunasayunasa.github.io/tartman_escape2/assets/ogp-20260908.jpg?v=20260908');assert.equal(await page.locator('meta[property="og:image:width"]').getAttribute('content'),'1280');assert.equal(await page.locator('meta[property="og:image:height"]').getAttribute('content'),'853');assert.equal(await page.locator('#app').getAttribute('data-atlas'),'8x8');assert.equal(await page.locator('#app').getAttribute('data-enemy-atlas'),'8x7');assert.equal(await page.locator('#key-count').getAttribute('aria-label'),'鍵 0 / 5');});
 await page.locator('#modal-action').click();await page.waitForTimeout(600);await screenshot('forest-mobile');
 await check('mobile rendering and iOS long-press protections are active',async()=>{assert.equal(await page.locator('#app').getAttribute('data-audio'),'ready');assert.equal(await page.locator('#scene').getAttribute('data-prewarmed'),'true');assert.ok(Number(await page.locator('#scene').getAttribute('data-render-scale'))<=.72);assert.match(await page.locator('meta[name="viewport"]').getAttribute('content'),/maximum-scale=1/);assert.equal(await page.locator('#run').evaluate(e=>getComputedStyle(e).touchAction),'none');assert.equal(await page.locator('#run').evaluate(e=>getComputedStyle(e).webkitUserSelect),'none');assert.equal(await page.locator('#run').evaluate(e=>e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))),false);});
 await check('walk and run',async()=>{const z=Number(await page.locator('#app').getAttribute('data-z'));await page.keyboard.down('KeyW');await page.keyboard.down('ShiftLeft');await page.waitForTimeout(600);await page.keyboard.up('KeyW');await page.keyboard.up('ShiftLeft');assert.ok(Number(await page.locator('#app').getAttribute('data-z'))<z-.5);assert.ok(await page.locator('#stamina-fill').evaluate(e=>parseFloat(e.style.width))<99);});
 await check('lock and pause',async()=>{await page.locator('#lock').click();await page.waitForTimeout(70);assert.ok(await page.locator('#run').isDisabled());await page.locator('#lock').click();await page.locator('#pause').click();await page.waitForTimeout(70);assert.equal(await page.locator('#app').getAttribute('data-state'),'paused');await page.locator('#modal-action').click();await page.waitForFunction(()=>document.querySelector('#app').dataset.state==='playing');});
 await check('flashlight toggle',async()=>{await page.locator('#light').click();assert.equal(await page.locator('#light').getAttribute('aria-pressed'),'false');await page.locator('#light').click();});
 await check('touch joystick and simultaneous run release on cancel',async()=>{const a=await page.locator('#stick').boundingBox(),b=await page.locator('#run').boundingBox(),session=await page.context().newCDPSession(page);const t1={x:a.x+a.width/2,y:a.y+15,id:1},t2={x:b.x+b.width/2,y:b.y+b.height/2,id:2};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[t1]});await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[t1,t2]});await page.waitForTimeout(250);assert.match(await page.locator('#run').getAttribute('class'),/held/);await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await page.waitForTimeout(50);assert.doesNotMatch(await page.locator('#run').getAttribute('class'),/held/);assert.equal(await page.locator('#knob').evaluate(e=>e.style.transform),'');await session.detach();});
 await page.setViewportSize({width:1280,height:900});await page.waitForTimeout(300);await screenshot('forest-desktop');
 await page.setViewportSize({width:360,height:640});await page.waitForTimeout(200);
 await check('small mobile controls stay inside screen',async()=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),360);for(const s of ['#stick','#run','#lock','#interact']){const b=await page.locator(s).boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=360&&b.y+b.height<=640,s);}});
 await screenshot('forest-small-mobile');
 await check('audio sliders persist and stay in the pause menu',async()=>{const b=await page.locator('#light').boundingBox();assert.ok(b.y>640*.6&&b.y+b.height<640);assert.equal(await page.locator('#mute').isVisible(),false);await page.locator('#pause').click();assert.ok(await page.locator('#mute').isVisible());assert.equal(await page.locator('.volume-settings input').count(),4);await page.locator('#music-volume').fill('12');assert.equal(await page.locator('#music-value').textContent(),'12');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tartman-audio-levels')).music),.12);await page.locator('#music-volume').fill('8');assert.equal(await page.locator('.map-area').count(),4);await screenshot('pause-map-mobile');await page.locator('#quality').click();assert.equal(await page.locator('#quality').getAttribute('aria-pressed'),'true');await page.locator('#quality').click();await page.locator('#modal-action').click();});
 await page.setViewportSize({width:390,height:844});
 const world=createZone(1).world;
 async function position(){return page.locator('#app').evaluate(el=>({x:Number(el.dataset.x),z:Number(el.dataset.z)}));}
 async function walkTo(goal){let route=pathfind(world,await position(),goal),held=new Set();try{for(let step=0;step<1200;step++){const p=await position();if(distance(p,goal)<.38)return;while(route.length&&distance(p,route[0])<.32)route.shift();const next=route[0]||goal,dx=next.x-p.x,dz=next.z-p.z,want=new Set();if(Math.abs(dx)>.16)want.add(dx>0?'KeyD':'KeyA');if(Math.abs(dz)>.16)want.add(dz>0?'KeyS':'KeyW');for(const k of held)if(!want.has(k))await page.keyboard.up(k);for(const k of want)if(!held.has(k))await page.keyboard.down(k);held=want;await page.waitForTimeout(65);}throw Error(`Could not reach ${JSON.stringify(goal)} from ${JSON.stringify(await position())}`);}finally{for(const k of held)await page.keyboard.up(k);}}
 await check('all four areas can be visited through live movement',async()=>{for(const [id,goal] of [['pond',{x:48,z:51}],['shrine',{x:49,z:23}],['cedar',{x:20,z:23}],['lantern',{x:21,z:50}]]){await walkTo(goal);await page.waitForTimeout(300);assert.equal(await page.locator('#app').getAttribute('data-area'),id);await screenshot(`area-${id}`);}});
 await check('key interaction updates HUD and triggers the grace period',async()=>{const key=createZone(1).keys[0];await walkTo(key);await page.waitForTimeout(80);assert.equal(await page.locator('#interact').textContent(),'鍵を拾う');await page.locator('#interact').click();await page.waitForTimeout(80);assert.equal(await page.locator('#key-count').getAttribute('aria-label'),'鍵 1 / 5');assert.equal(await page.locator('#app').getAttribute('data-enemy'),'absent');});
 await check('reading a note pauses and resumes the world',async()=>{await walkTo({x:17,z:50});await page.locator('#interact').click();await page.waitForTimeout(100);assert.equal(await page.locator('#app').getAttribute('data-state'),'reading');await page.locator('#modal-action').click();await page.waitForTimeout(100);assert.equal(await page.locator('#app').getAttribute('data-state'),'playing');});
}};
